exports.colors = {
    test_primary: "#05DBF3",
    test_secondary: "#CDF8FD ",
    test_background_container: "#231F20",
    test_background_card: "#2E2A2B",
    test_orange_primary: "#F2E206",
    test_orange_secondary: "#F9F182",
    test_hover_neon_blue: "#04AFC2",
    test_secondary_blue: "#82EDF9",
    test_secondary_black: "#4F4C4D",
    test_danger: "#F12816",
    test_secondary_danger: "#F8938A",
    test_btn_secondary: "#D9FAFD",
    test_switch_text_secondary: "#918F8F",
    test_btn_error: "#F8938A",
    test_text_secondary: "#D3D2D2",
    test_gray_primary: "#918F8F",
    error: "#F45345",
    test_green: "#C8FDD4",
    test_green_text: "#08A418",
    test_red: "#FFD2CE",
    test_orange: "#FFFCCE",
    test_orange_text: "#E56E00",
    test_text_black: "#212B36",
  };